/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrinkingWaterRouteImport } from './routes/drinking-water'
import { Route as FlareGasRouteImport } from './routes/flare-gas'
import { Route as ProjectDeliveryRouteImport } from './routes/project-delivery'
import { Route as RenewableEnergyRouteImport } from './routes/renewable-energy'
import { Route as WaterSystemsRouteImport } from './routes/water-systems'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinkingWaterRoute = DrinkingWaterRouteImport.update({
  id: '/drinking-water',
  path: '/drinking-water',
  getParentRoute: () => rootRouteImport,
} as any)
const FlareGasRoute = FlareGasRouteImport.update({
  id: '/flare-gas',
  path: '/flare-gas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectDeliveryRoute = ProjectDeliveryRouteImport.update({
  id: '/project-delivery',
  path: '/project-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewableEnergyRoute = RenewableEnergyRouteImport.update({
  id: '/renewable-energy',
  path: '/renewable-energy',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterSystemsRoute = WaterSystemsRouteImport.update({
  id: '/water-systems',
  path: '/water-systems',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drinking-water': typeof DrinkingWaterRoute
  '/flare-gas': typeof FlareGasRoute
  '/project-delivery': typeof ProjectDeliveryRoute
  '/renewable-energy': typeof RenewableEnergyRoute
  '/water-systems': typeof WaterSystemsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drinking-water': typeof DrinkingWaterRoute
  '/flare-gas': typeof FlareGasRoute
  '/project-delivery': typeof ProjectDeliveryRoute
  '/renewable-energy': typeof RenewableEnergyRoute
  '/water-systems': typeof WaterSystemsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drinking-water': typeof DrinkingWaterRoute
  '/flare-gas': typeof FlareGasRoute
  '/project-delivery': typeof ProjectDeliveryRoute
  '/renewable-energy': typeof RenewableEnergyRoute
  '/water-systems': typeof WaterSystemsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drinking-water'
    | '/flare-gas'
    | '/project-delivery'
    | '/renewable-energy'
    | '/water-systems'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drinking-water'
    | '/flare-gas'
    | '/project-delivery'
    | '/renewable-energy'
    | '/water-systems'
  id:
    | '__root__'
    | '/'
    | '/drinking-water'
    | '/flare-gas'
    | '/project-delivery'
    | '/renewable-energy'
    | '/water-systems'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrinkingWaterRoute: typeof DrinkingWaterRoute
  FlareGasRoute: typeof FlareGasRoute
  ProjectDeliveryRoute: typeof ProjectDeliveryRoute
  RenewableEnergyRoute: typeof RenewableEnergyRoute
  WaterSystemsRoute: typeof WaterSystemsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinking-water': {
      id: '/drinking-water'
      path: '/drinking-water'
      fullPath: '/drinking-water'
      preLoaderRoute: typeof DrinkingWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flare-gas': {
      id: '/flare-gas'
      path: '/flare-gas'
      fullPath: '/flare-gas'
      preLoaderRoute: typeof FlareGasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-delivery': {
      id: '/project-delivery'
      path: '/project-delivery'
      fullPath: '/project-delivery'
      preLoaderRoute: typeof ProjectDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewable-energy': {
      id: '/renewable-energy'
      path: '/renewable-energy'
      fullPath: '/renewable-energy'
      preLoaderRoute: typeof RenewableEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water-systems': {
      id: '/water-systems'
      path: '/water-systems'
      fullPath: '/water-systems'
      preLoaderRoute: typeof WaterSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrinkingWaterRoute: DrinkingWaterRoute,
  FlareGasRoute: FlareGasRoute,
  ProjectDeliveryRoute: ProjectDeliveryRoute,
  RenewableEnergyRoute: RenewableEnergyRoute,
  WaterSystemsRoute: WaterSystemsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
